#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <somnus_icons.h>

int32_t somnus_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm somnus!");

    return 0;
}
