\
/*
 * Somnus - BadUSB Logger for Flipper Zero
 * Generated by Flipper Zero GPT
 *
 * This app allows users to:
 * - Set the active computer name
 * - Save it in a .current_computer file
 * - Log entries to a computer-specific folder
 * - These logs can then be written to by BadUSB scripts
 */

#include <furi.h>
#include <furi_hal.h>
#include <gui/gui.h>
#include <input/input.h>
#include <dialogs/dialogs.h>
#include <storage/storage.h>
#include <text_input.h>
#include <stdlib.h>
#include <string.h>

#define SOMNUS_BASE_PATH "/ext/somnus"
#define CURRENT_COMPUTER_FILE "/ext/somnus/.current_computer"
#define LOG_FILENAME "log.txt"
#define MAX_NAME_LENGTH 64

typedef struct {
    FuriString* current_computer;
    Storage* storage;
    DialogsApp* dialogs;
} SomnusApp;

void somnus_write_current_computer(SomnusApp* app) {
    File* file = storage_file_open(app->storage, CURRENT_COMPUTER_FILE, FSAM_WRITE, FSOM_CREATE_ALWAYS);
    if(file) {
        storage_file_write(file, furi_string_get_cstr(app->current_computer), furi_string_size(app->current_computer));
        storage_file_close(file);
    }
}

void somnus_create_computer_folder(SomnusApp* app) {
    char folder_path[128];
    snprintf(folder_path, sizeof(folder_path), "%s/%s", SOMNUS_BASE_PATH, furi_string_get_cstr(app->current_computer));
    storage_common_mkdir(app->storage, folder_path);
}

void somnus_add_log_entry(SomnusApp* app, const char* message) {
    char file_path[256];
    snprintf(file_path, sizeof(file_path), "%s/%s/%s", SOMNUS_BASE_PATH, furi_string_get_cstr(app->current_computer), LOG_FILENAME);

    File* file = storage_file_open(app->storage, file_path, FSAM_WRITE, FSOM_OPEN_APPEND);
    if(file) {
        char timestamp[64];
        furi_rtc_datetime_t dt;
        furi_rtc_get_datetime(&dt);
        snprintf(timestamp, sizeof(timestamp), "[%04d-%02d-%02d %02d:%02d:%02d] ",
                 dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second);

        storage_file_write(file, timestamp, strlen(timestamp));
        storage_file_write(file, message, strlen(message));
        storage_file_write(file, "\n", 1);
        storage_file_close(file);
    }
}

void somnus_prompt_for_computer_name(SomnusApp* app) {
    FuriString* name = furi_string_alloc();
    text_input_get_text(app->dialogs, name, "Enter computer name", true);
    furi_string_set(app->current_computer, furi_string_get_cstr(name));
    furi_string_free(name);

    somnus_create_computer_folder(app);
    somnus_write_current_computer(app);
}

int32_t somnus_app(void* p) {
    UNUSED(p);

    SomnusApp app;
    app.storage = furi_record_open("storage");
    app.dialogs = furi_record_open("dialogs");
    app.current_computer = furi_string_alloc();

    // Prompt for computer name
    somnus_prompt_for_computer_name(&app);

    // Sample manual log entry
    somnus_add_log_entry(&app, "Session started.");

    furi_string_free(app.current_computer);
    furi_record_close("storage");
    furi_record_close("dialogs");

    return 0;
}
